-- Fictitious learning content for local demonstration. Not production content.
insert into public.courses (id,title,description,category,position,published) values ('30000000-0000-4000-8000-000000000001','Trouver son rythme en famille','Une semaine souple, des repères solides. Posez les bases d’une organisation qui vous ressemble.','Organisation',1,true) on conflict(id) do nothing;
insert into public.courses (id,title,description,category,position,published) values ('30000000-0000-4000-8000-000000000002','Faire ses premiers pas','Clarifiez votre intention et repérez les ressources utiles pour commencer sereinement.','Pour commencer',2,true) on conflict(id) do nothing;
insert into public.courses (id,title,description,category,position,published) values ('30000000-0000-4000-8000-000000000003','Garder une trace des découvertes','Un portfolio simple pour voir le chemin parcouru, sans tout conserver.','Apprentissages',3,true) on conflict(id) do nothing;
insert into public.lessons (id,course_id,title,minutes,position,body,exercise) values ('40000000-0000-4000-8000-000000000001','30000000-0000-4000-8000-000000000001','Observer avant de planifier',6,1,'Avant de remplir un calendrier, prenez le temps d’observer votre famille. À quel moment votre enfant est-il le plus disponible ? Quelles activités vous donnent de l’énergie ? Les réponses vous aideront à choisir des repères réalistes.

Pendant deux ou trois jours, notez les moments de concentration, les besoins de mouvement et les pauses spontanées. Il ne s’agit pas d’évaluer la performance de votre famille : cherchez simplement ce qui facilite votre quotidien.

Choisissez ensuite deux points d’appui : un moment pour commencer ensemble et un moment pour terminer. Entre les deux, gardez de la place pour les questions, les détours et le repos. Une routine utile vous soutient; elle peut évoluer.','Notez un moment où votre famille se sent disponible. Ajoutez ensuite un premier rendez-vous dans « Ma semaine ».') on conflict(id) do nothing;
insert into public.lessons (id,course_id,title,minutes,position,body,exercise) values ('40000000-0000-4000-8000-000000000002','30000000-0000-4000-8000-000000000001','Construire une semaine souple',8,2,'Commencez par ce qui est déjà présent : repas, rendez-vous, sorties et temps de repos. Répartissez ensuite quelques intentions d’apprentissage dans les espaces disponibles. Évitez de planifier chaque minute.

Un mardi peut commencer par une lecture partagée, se poursuivre par une promenade d’observation et se terminer par un temps calme. Les durées dépendent de votre famille. Une activité commune peut donner lieu à des défis différents selon les enfants.

Prévoyez un espace libre chaque jour. Si une activité ne fonctionne pas, déplacez-la ou simplifiez-la. Le calendrier sert à rendre vos intentions visibles, pas à créer une obligation de tout accomplir.','Planifiez deux activités et une pause pour mardi. Choisissez « Toute la famille » lorsque l’activité est partagée.') on conflict(id) do nothing;
insert into public.lessons (id,course_id,title,minutes,position,body,exercise) values ('40000000-0000-4000-8000-000000000003','30000000-0000-4000-8000-000000000001','Ajuster sans culpabiliser',5,3,'À la fin de la semaine, prenez quelques minutes pour regarder ce qui a aidé votre famille. Demandez à chacun de raconter une découverte et un moment difficile. Écoutez sans chercher tout de suite une solution.

Conservez un repère qui fonctionne et modifiez une seule chose pour la semaine suivante. Ce petit ajustement est plus facile à observer qu’un nouveau planning complet.

Une activité reportée ne signifie pas qu’aucun apprentissage n’a eu lieu. Vos observations et vos échanges permettent de comprendre le chemin parcouru. Pour les démarches officielles, consultez les ressources gouvernementales liées dans la bibliothèque.','Choisissez un repère à conserver la semaine prochaine et racontez pourquoi dans une note personnelle.') on conflict(id) do nothing;
insert into public.lessons (id,course_id,title,minutes,position,body,exercise) values ('40000000-0000-4000-8000-000000000004','30000000-0000-4000-8000-000000000002','Clarifier son intention',7,1,'Votre projet commence par une conversation. Qu’aimeriez-vous rendre possible dans votre quotidien ? Quels sont les besoins de votre enfant et les ressources dont vous disposez ?

Écrivez trois intentions concrètes, comme lire ensemble régulièrement ou apprendre à observer la nature. Distinguez vos envies des démarches administratives : les ressources officielles vous permettront de vérifier ces dernières.

Les cours ParentEd sont destinés aux parents et proposent des pistes d’organisation. Ils ne remplacent pas les informations gouvernementales ni un accompagnement professionnel adapté à votre situation.','Écrivez vos trois intentions. Consultez ensuite le portail officiel depuis la bibliothèque.') on conflict(id) do nothing;
insert into public.lessons (id,course_id,title,minutes,position,body,exercise) values ('40000000-0000-4000-8000-000000000005','30000000-0000-4000-8000-000000000003','Choisir une trace qui raconte',6,1,'Une trace utile raconte une découverte : une photo d’une construction, quelques phrases dictées ou un dessin accompagné d’une question. Conserver moins de traces, avec un peu de contexte, facilite leur relecture.

Notez la date, l’activité et ce que votre enfant souhaite raconter. Privilégiez ses mots et protégez sa vie privée. Les documents de votre espace familial ne sont pas publiés dans la communauté.

Prenez régulièrement le temps de revoir ces traces ensemble. Cet outil aide à observer les apprentissages; il ne constitue pas automatiquement un dossier répondant aux exigences officielles.','Choisissez un document sans données sensibles et ajoutez-le à votre dossier familial privé.') on conflict(id) do nothing;
insert into public.resources (id,title,description,category,url,source,checked_at) values ('80000000-0000-4000-8000-000000000001','L’enseignement à la maison au Québec','Le point de départ officiel pour retrouver les informations du ministère. Nos cours sont un accompagnement indépendant.','Pour commencer','https://www.quebec.ca/education/prescolaire-primaire-et-secondaire/programmes-formations-evaluation/enseignement-maison','Gouvernement du Québec','2026-09-05') on conflict(id) do nothing;
insert into public.resources (id,title,description,category,url,source,checked_at) values ('80000000-0000-4000-8000-000000000002','Démarche et étapes','Retrouvez les étapes et les documents à consulter directement auprès de la source officielle.','Démarches','https://www.quebec.ca/education/prescolaire-primaire-et-secondaire/programmes-formations-evaluation/enseignement-maison/demarche-etapes','Gouvernement du Québec','2026-09-05') on conflict(id) do nothing;
insert into public.resources (id,title,description,category,url,source,checked_at) values ('80000000-0000-4000-8000-000000000003','Services de soutien','Explorez les services publics décrits par le ministère et vérifiez les modalités qui concernent votre situation.','Accompagnement','https://www.quebec.ca/education/prescolaire-primaire-et-secondaire/programmes-formations-evaluation/enseignement-maison/services-soutien','Gouvernement du Québec','2026-09-05') on conflict(id) do nothing;
insert into public.events (id,title,description,date,time,location,organizer,age,published) values ('70000000-0000-4000-8000-000000000001','Une matinée au jardin botanique','Observer les couleurs de l’automne et remplir un petit carnet nature ensemble. Rencontre fictive et gratuite pour la démonstration. Chaque enfant reste sous la supervision de son parent. Annulation possible depuis cette page.','2026-09-15','10:00','Montréal · Entrée du jardin','Camille — ParentEd (fictif)','6–12 ans',true) on conflict(id) do nothing;
insert into public.events (id,title,description,date,time,location,organizer,age,published) values ('70000000-0000-4000-8000-000000000002','Café des parents : nos routines','Un temps d’échange pour partager ce qui fonctionne, poser ses questions et repartir avec une idée. Rencontre fictive et gratuite. Les parents restent responsables de leurs enfants. Désinscription libre.','2026-09-18','13:30','Montréal · Bibliothèque de quartier','Sami — membre (fictif)','Parents et enfants',true) on conflict(id) do nothing;
